import "../theme/globals.css";
import Head from "next/head";
import { AppType } from "next/dist/shared/lib/utils";
import MetamaskProvider from "../features/Metamask/MetamaskContext";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Swap App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MetamaskProvider>
        <Component {...pageProps} />
      </MetamaskProvider>
    </>
  );
};

export default MyApp;
